export GITHUB_API_TOKEN=2a1adb0c6ace839497eff5791fae723a08b41181
export HOMEBREW_GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GRADLE_HOME=/usr/local/Cellar/gradle/2.3
export HIVE_HOME=/usr/local/Cellar/hive/0.13.1/libexec
export HCAT_HOME=/usr/local/Cellar/hive/0.13.1/libexec/hcatalog
export GNUTERM=aqua
export GOPATH=~/lib/go
export ANDROID_HOME=~/Library/Android/sdk
export SONAR_RUNNER_HOME=/usr/local/Cellar/sonar-runner/2.4/libexec
export JENV_ROOT=/usr/local/opt/jenv
export JAVA_OPTS='-Djava.net.preferIPv4Stack=true'
